apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sigmaops-ingress
  labels:
    app: sigmaops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: sigmaops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sigmaops-service
                port:
                  number: 80
