apiVersion: v1
kind: Secret
metadata:
  name: sigmaops-secrets
  labels:
    app: sigmaops
type: Opaque
stringData:
  DB_NAME: claro_sigmaops
  DB_USER: clarosigma
  DB_PASSWORD: test123
  DB_HOST: "10.68.12.31"
  SECRET_KEY: "django-secure-secret-key-change-in-production"
